// Code generated by go generate; DO NOT EDIT.
// This file was generated by Vuego generator.
package main

import "github.com/chanwit/vuego"

var _ = vuego.New

func (this *Data) AddToItems(val *Item) {
	this.Items = append(this.Items, val)
	this.Value.Get("items").Call("push", vuego.ToJSON(val))
}

func (this *Data) GetTitle() string {
	this.Title = this.Value.Get("title").String()
	return this.Title
}

func (this *Data) SetTitle(val string) {
	this.Title = val
	this.Value.Set("title", val)
}

func (this *Data) GetNewItem() string {
	this.NewItem = this.Value.Get("newItem").String()
	return this.NewItem
}

func (this *Data) SetNewItem(val string) {
	this.NewItem = val
	this.Value.Set("newItem", val)
}

