// Code generated by go generate; DO NOT EDIT.
// This file was generated by Vuego generator.
package main

import "github.com/chanwit/vuego"

var _ = vuego.New

func (this *Item) GetText() string {
	this.Text = this.Value.Get("text").String()
	return this.Text
}

func (this *Item) SetText(val string) {
	this.Text = val
	this.Value.Set("text", val)
}

func (this *Item) GetChecked() bool {
	this.Checked = this.Value.Get("checked").Bool()
	return this.Checked
}

func (this *Item) SetChecked(val bool) {
	this.Checked = val
	this.Value.Set("checked", val)
}

